repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
-   repo: https://github.com/adithyabsk/mirrors-rubocop
    rev: v0.80.1
    hooks:
    -   id: rubocop
        additional_dependencies: ['rubocop-performance:1.5.2', 'rubocop-rspec:1.38.1']
-   repo: https://github.com/adithyabsk/mirrors-reek
    rev: v5.6.0
    hooks:
      -   id: reek
-   repo: https://github.com/adithyabsk/mirrors-rails-best-practices
    rev: v1.20.0
    hooks:
      -   id: rails_best_practices
-   repo: https://github.com/adithyabsk/mirrors-brakeman
    rev: v4.8.0
    hooks:
      -   id: brakeman
          args: ["--no-pager"]
          pass_filenames: false
