detectors:
  # TODO: Find a way to remove these I just ignored the ones that were
  # hard to fix
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  NilCheck:
    enabled: false
  FeatureEnvy:
    exclude:
      - "CartItemsController#init_or_increment"
  UtilityFunction:
    exclude:
      - "LedgerEntriesController#send_status_email"
      - "LedgerEntry#is_user?"
  TooManyStatements:
    enabled: true
    exclude:
      - initialize
    max_statements: 25
  TooManyInstanceVariables:
    exclude:
      - UserMailer

# Make Rails setup work (these need to be ignored)
directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false

exclude_paths:
  - db
