inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rspec

RSpec/ExampleLength:
  Enabled: false

AllCops:
  Exclude:
    - '.git/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
  TargetRubyVersion: 2.7
